### ISSUE TITLE
This broke the game

### ISSUE THREAD

**Issue by CageStooge** [Fireball14/DSP-Mods#1]
Started a new game with this, got to the point where I got warpers, and now none of the vessels will warp anywhere. I've got over 300 hours on another save game, spanning multiple stars, so I know how the warpers work. Removing the mod did not resolve the issue either. They all just refuse to launch

**Comment by Fireball14** [comment]
Hey! Sorry to hear that. Just drop me your save game, and I'll take a look what's happening. List of other mods you use may be also useful.

**Comment by CageStooge** [comment]
Disregard. I'm an idiot. I thought I had unlocked Logisitcs carrier engine Level 4 and I had not. So they can't use warpers yet. DOH! I'll unlock that and report back.

**Comment by CageStooge** [comment]
OK, unlocked carrier engine level IV and the warp drives fired. Sorry about that. Nice mod!

**Comment by Fireball14** [comment]
Yay! Good luck!
