### ISSUE TITLE
[DistributeSpaceWarpers] Messes up Advanced Miner UI

### ISSUE THREAD

**Issue by HordeBies** [Fireball14/DSP-Mods#12]
How it should look:
![Screenshot_80](https://user-images.githubusercontent.com/73644073/152644400-7711c5cc-e1ee-4e2a-bf62-a267f766bc33.png)

How it looks:
![image](https://user-images.githubusercontent.com/73644073/152644466-97d1f76d-8837-4396-bbd5-bcf7237f02df.png)

**Comment by Fireball14** [comment]
Version v 1.0.10 has fixed it.
