### ISSUE TITLE
Error when starting game, spacewarpers

### ISSUE THREAD

**Issue by nyqeest** [Fireball14/DSP-Mods#13]
When i start the game i occured an error. After start I have 6-8 stacks of spacewarpers in my inventory. I noticed that when i save/load the game a couple of times and each time spacewarpers would appear in my inventory. one time they did not appear anymore and the game started without errors

![image](https://user-images.githubusercontent.com/52583656/154522242-012362dd-3204-4137-9327-29ad9925e45d.png)

**Comment by Fireball14** [comment]
Try 1.0.10. Should work.
