### ISSUE TITLE
Problems with version 0.6.17.6112

### ISSUE THREAD

**Issue by Marval89** [Fireball14/DSP-Mods#2]
Starting from update from 01.04.2021 there is the problem with "SetStationStorage". Are you able to fix this mod? Like it a lot.

**Comment by nyqeest** [comment]
same here :)
![image](https://user-images.githubusercontent.com/52583656/113457286-bbbbcf00-940f-11eb-82bf-4d46e3860d61.png)

**Comment by Fireball14** [comment]
Will fix it tomorrow, thx for report!

**Comment by Fireball14** [comment]
Scratch that, fix is up. Good luck!
