### ISSUE TITLE
Issue with the latest update for DistributedSpaceWarpers

### ISSUE THREAD

**Issue by Korrakore** [Fireball14/DSP-Mods#3]
The recent update didn't create a config file in my case, and also the ILS in game doesn't actually add the 6'th slot, it only adds a blank slot where you cannot select anything. I have attached a screenshot to explain better. Also there are screenshots for the config editor and the mods I use, maybe it could be a compatibility issue. Thanks

![Screenshot (15)](https://user-images.githubusercontent.com/81384651/113492261-de271880-94f3-11eb-8b83-d2b467319802.png)

![Screenshot (18)](https://user-images.githubusercontent.com/81384651/113492312-2c3c1c00-94f4-11eb-930b-bc81cc9889b5.png)

![Screenshot (17)](https://user-images.githubusercontent.com/81384651/113492316-2fcfa300-94f4-11eb-9e66-3c33c5f2d0a6.png)

**Comment by Fireball14** [comment]
Hey there, so there should not be any config file, and slot 6 is hidden, so not to cause any confusion.
Note that my mod will hide anything over 5 slots, so other mods that really on 6+ slots in any station will not work with it.
All in all, this should not change your station UI in any way, it should just work in background without changing any station rules.

You say it adds a blank slot, but I don't see it on your screen shot. Maybe I'm blind. :) Anyway, if you have any questions, you can always find me in discord at ShadowAngel#9985.

**Comment by Korrakore** [comment]
Hey there, by blank slot I meant that in the first screenshot, look after 5 slots there is a gap that's close to the size of a slot, earlier, I don't exactly know if this was from the Auto Station Config mod or your mod, but I used to see a 6'th slot where you can't add anything else, and that slot purely is allocated for Warpers, so maybe could be a confusion by me as to which mod did that, but anyways, just wanted to let you know in case it could be a problem, I did notice a lot of mods breaking due to the recent update so just wanted to make sure, thanks anyways, and sure, if I get any questions, I will definitely ask you on Discord, so have a great day/night.

**Comment by Korrakore** [comment]
Hey just wanted to let you know, I found out the spacing problem, apparently with the mod enabled, your 6'th slot should be hidden, it is, but it leaves a blank space instead of keeping it seamless, I have attached screenshots of before and after and you will realize what I meant, maybe check the code if there is some error regarding this.

With Mod Enabled
![Screenshot (15)](https://user-images.githubusercontent.com/81384651/113497566-f6faf280-9522-11eb-8513-e34806406c4b.png)

With Mod Disabled 
![Screenshot (21)](https://user-images.githubusercontent.com/81384651/113497569-00845a80-9523-11eb-9f83-32c2d03b803b.png)

**Comment by Fireball14** [comment]
oh I got it, thx. Its just that I only manipulated visual slots array and never touched ui size values. This will minimize comparability problems. Anyway I have an idea to create config, to let you see 6th slot and configure it a bit.

**Comment by Korrakore** [comment]
Well it would be great if that's doable, please let me know. Thanks. Have a great day/night.

**Comment by Fireball14** [comment]
Update 1.0.3 is up.
I found what causing visual empty space bug. To fix it, I would need to patch method that is commonly used by other mods. I rather not do that for small visual glitch for sake of comparability.
Other than that I added few config options including ability to show hidden slot. 
If you have any other issues pls let me know :)

**Comment by Korrakore** [comment]
Well you already did enough, thanks, if I have any other doubts I'll surely let you know, and one more thing, you actually spelt remote wrong in the description, it's written remoute there, maybe change that. Anyways, thanks again, and have a great day/night.

![Screenshot (27)](https://user-images.githubusercontent.com/81384651/113515166-69ee8280-9590-11eb-825a-1ee838bd903d.png)

**Comment by Fireball14** [comment]
Yeah English is not my main language x) Sorry. Will be fixed on next upload. Have a nice day.
