### ISSUE TITLE
[Feature request] Compatibility with GigaStations

### ISSUE THREAD

**Issue by Razunter** [Fireball14/DSP-Mods#5]
Mod isn't compatible with [GigaStations v2](https://dsp.thunderstore.io/package/Taki7o7/GigaStations_v2/), limits Planetary Giga Stations to 5 slots instead of 12.

**Comment by Fireball14** [comment]
Please change config value "ShowWarperSlot" to true.
This will fix UI issues.

**Comment by Razunter** [comment]
Looks lite it helped, thx. It's weird, though, that it affects Planetary Stations.

**Comment by Fireball14** [comment]
There is no easy way to hide specific slot. So it's basically just cuts out anything over 5 slots. It's not a problem for default game, but problem for mods that change default UI.
