### ISSUE TITLE
Disable/removal of the mod will leave 6th slot on all ILS visible

### ISSUE THREAD

**Issue by gotnoface** [Fireball14/DSP-Mods#6]
As mentioned in the title, when the mod is disabled, all already built ILS will show the previously hidden slot with warpers available. It's more or less just a cosmetic problem, because player can just ignore the slot.

I have a proposal to include an option config that will forcibly reset all ILS back to 5 slots (hidden or otherwise) for easier and cleaner removal of the mod in case of testing their own mod or otherwise.

**Comment by Fireball14** [comment]
Hey I did have thought about it. but I have come to conclusion, it would be cumbersome to do. There is no clean way to tell people - "Hey, if you go in to config set this true, then go in to game, save it, then back out than uninstall mod, that's when you have removed mod from game." 99% would just don't know it's there and that how you do it. So I figured I'll just skip it.

Fun fact, if you leave mod on, but set default logic to store, you would basically disable it.

Anyway if its a big issue, just tell me and I get on it. Cos its gonna take 2-3 hours to implement.

**Comment by gotnoface** [comment]
> Fun fact, if you leave mod on, but set default logic to store, you would basically disable it.

Yeah I figured that out too. This issue is not that big of a problem for me or my own tinkering with mods. It's just something I found and reported. 
Implementing it would give modder a way to re-vanillize their save, without having to manually replace all their ILS with new ones.
But, if you find it cumbersome or a waste of effort, I personally wouldn't mind not having it.

Maybe you can just leave it as known issue and leave users with your proposed solution, so that there wouldn't be more reoprts about this.
