### ISSUE TITLE
Mod conflict with GigaStations v2

### ISSUE THREAD

**Issue by Vladyslav-Krot** [Fireball14/DSP-Mods#7]
The mod conflict with GigaStations v2

https://dsp.thunderstore.io/package/Taki7o7/GigaStations_v2/2.0.7/

5 slots display with this mod instead 12 in GigaStation

**Comment by Fireball14** [comment]
Please change config value "ShowWarperSlot" to true.
This will fix UI issues.

For more info see https://github.com/Fireball14/DSP-Mods/issues/5
