### ISSUE TITLE
Distribute warpers mod appears to be broken in v 0.7.18.7063

### ISSUE THREAD

**Issue by lukaskucinski** [Fireball14/DSP-Mods#8]
Interstellar logistics stations receive warpers but they do not show up in the warper slot, they simply vanish. When mod is disabled/uninstalled cannot created dedicated slot for warpers.  Throws error that duplicate slot for warpers already exists. Must rebuild logistic station to fix issue.

**Comment by lukaskucinski** [comment]
Correction. This is a conflict issue with another mod. [BetterLogisticStations](https://dsp.thunderstore.io/package/r0uv3n/BetterLogisticsStations/). When this is disabled the warper distribution works as expected. Sorry for the false alarm.

**Comment by Fireball14** [comment]
Hey there, I did tried to make it compatible with BetterLogisticStations, but author of that mod did not upload main mod scripts to github, so nothing I can do. Sorry.

**Comment by lukaskucinski** [comment]
No worries. Thanks! Your mod is awesome btw
